---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TARGET=localhost
        - CONNECTION=local
        - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"
      install:
        - sudo pip install -U setuptools
        - sudo pip install ansible
        - ansible-galaxy install FGtatsuro.python-requirements
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      before_script:
        - docker run -it -d --name container fgtatsuro/infra-bridgehead:debian-jessie /bin/bash
      after_script:
        - docker rm -f container
      env:
        - TARGET=container
        - CONNECTION=docker
    - os: linux
      language: python
      python: 2.7
      before_install:
        - rvm install 2.2.3
      env:
        - TARGET=localhost
        - CONNECTION=local
        - EXTRA_VARS="virtualbox_apt_repository='deb http://download.virtualbox.org/virtualbox/debian precise contrib' virtualbox_allow_unauthenticated='no'"
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env:
        - TARGET=localhost
        - CONNECTION=local
        - EXTRA_VARS="virtualbox_apt_repository='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' virtualbox_allow_unauthenticated='no'"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

install:
  - pip install ansible
  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.)
  - ansible-galaxy install FGtatsuro.python-requirements

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} --connection=${CONNECTION} --extra-vars="${EXTRA_VARS}" -vvvv
  - bundle install
  - bundle exec rake spec SPEC_TARGET=${TARGET}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
